name: Automação de Testes

on:
  workflow_dispatch:
    inputs:
      run_tests:
        description: 'Rodar testes?'
        required: true
        default: 'true'
        type: boolean

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Clean Allure Results
        if: ${{ github.event.inputs.run_tests == 'true' }}
        run: rm -rf allure-results/*

      - name: Build & Run Tests
        if: ${{ github.event.inputs.run_tests == 'true' }}
        run: mvn clean verify

      - name: Generate Allure Report
        if: ${{ github.event.inputs.run_tests == 'true' }}
        run: mvn allure:report

      - name: Publish Allure Report
        if: ${{ github.event.inputs.run_tests == 'true' }}
        uses: allure-framework/allure-action@v2
        with:
          results: allure-results

      - name: Upload Test Results
        if: ${{ github.event.inputs.run_tests == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/
